from .nodes.audio_latent import NODE_CLASS_MAPPINGS as _ACM, NODE_DISPLAY_NAME_MAPPINGS as _ADM
from .nodes.extend_mask import NODE_CLASS_MAPPINGS as _ECM, NODE_DISPLAY_NAME_MAPPINGS as _EDM

NODE_CLASS_MAPPINGS = {**_ACM, **_ECM}
NODE_DISPLAY_NAME_MAPPINGS = {**_ADM, **_EDM}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
